ERROR 2021-01-06 19:44:04,457 root : Unable to conect to the server: HTTPConnectionPool(host='mysite', port=8000): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20292bcc88>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR 2021-01-06 19:45:04,519 root : Unable to conect to the server: HTTPConnectionPool(host='mysite', port=8000): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20292bcda0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR 2021-01-06 19:46:04,585 root : Unable to conect to the server: HTTPConnectionPool(host='mysite', port=8000): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20292bcc50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR 2021-01-20 14:01:32,584 root : Unable to conect to the server: HTTPConnectionPool(host='mysite', port=8000): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94b71f7c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR 2021-01-20 14:05:51,779 root : Unable to conect to the server: HTTPConnectionPool(host='mysite', port=8000): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe17d478c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
